README.md
=> add go to fenced code blocks

web/func.go
Signed-off-by: Peter Edge <peter.edge@gmail.com>
=> Simplify ParseTruthyFalsy function

config/kafka.go, config/oracle.go, config/server.go, examples/servers/mysql-saved-items/service/saveditems.go, server/esxhealthcheck.go
Backlog of small changes I've noticed poking around Gizmo the last few days.
=> Misc cleanup

README.md, doc.go, server/doc.go, server/service.go
See discussion at https://nytimes.slack.com/archives/golang-nuts/p1463502598001465
=> Clarify service interface JSONEndpoints() documentation

examples/servers/json/service/mostpopular.go, examples/servers/mixed/service/mostpopular.go, examples/servers/rpc/service/mostpopular.go, examples/servers/simple/service/mostpopular.go
See https://github.com/NYTimes/gizmo/issues/57
=> Change server examples to use `web.Vars`

README.md, config/combined/config.go, config/doc.go, config/postgresql/postgresql.go
🚧 
Would you guys be interested in this?
=> Add support for Postgresql

config/metrics/metrics.go, examples/pubsub/sqs-sub/service/sub.go, server/metrics.go, server/metrics_test.go, server/rpc_server.go, server/server.go, server/simple_server.go
This PR is pending go-kit/kit#313
=> Metrics updates to match go-kit/kit/metrics changes

config/mysql/mysql.go
As per our discussion from Friday, this adds read and write timeouts as well as a "catch-all" field.
=> Add mysql config options

.travis.yml, server/config.go, server/http_server.go, server/http_server_go18.go, server/rpc_server.go, server/server.go, server/simple_server.go
=> server: support IdleTimeout

pubsub/aws/awspub_test.go, pubsub/aws/awssub_test.go, pubsub/gcp/gcp.go, pubsub/gcp/gcp_test.go
=> Updating GCP pubsub to match new API

server/service_pre_go17.go
Removing an unused import for pre-1.7 users that led to compilation errors.
=> Remove unused import

server/config.go, server/server.go
=> Adding server.Config.LogJSONFormat

server/rpc_server.go, server/simple_server.go
=> default handler for 404 metrics to '__404__'

examples/pubsub/README.md, examples/pubsub/gcp-pubsub/.env, examples/pubsub/gcp-pubsub/README.md, examples/pubsub/gcp-pubsub/main.go, pubsub/gcp/gcp.go
Added GCP usage example into examples/pubsub folder. Closes #146
=> gcp: Added GCP usage example

pubsub/http/pub.go, pubsub/http/pub_test.go
Also, slowly moving to the proper "accept interfaces, return structs" style.
=> expanding HTTP publishers to implement the MultiPublisher interface

pubsub/aws/aws.go
We're having trouble using Role based authorization.  Could we do something like this?
=> Prioritize Role over environment variables

server/simple_server.go
Fixes https://github.com/NYTimes/gizmo/issues/183
Fixes https://github.com/NYTimes/gizmo/issues/184
Tested it locally with a simple server and it worked, and the tests pass locally as well. 
**However** I'm not familiar with the code base, so a maintainer should review any potential regressions from this code change.
=> Remove unnecessary body close

README.md, auth/gcp/metadata.go, auth/verify.go, config/aws/aws.go, config/config.go, config/mysql/mysql.go, config/postgresql/postgresql.go, doc.go, examples/go.sum, observe/observe.go, pubsub/aws/aws.go, pubsub/doc.go, pubsub/gcp/gcp.go, pubsub/http/pub.go, pubsub/kafka/kafka.go, pubsub/pubsubtest/doc.go, server/doc.go, server/kit/server.go
The canonical import path thing should help with godoc.
=> Update travis badge in readme and add canonical import paths

server/kit/kitserver_test.go, server/kit/log.go
=> Adding log levels to kit/server.Log*Msg funcs

README.md
Just a small fix typo
packge -> package
=> Fix typo (packge -> package)
