nytimes/gizmo

CONTRIBUTING.md
Makefile
config/doc.go
doc.go
pubsub/doc.go
pubsub/kafka.go
web/doc.go
web/func.go
web/func_test.go

This adds a Makefile for common development tasks. Some other places this is used:
https://github.com/peter-edge/go-openflights
https://github.com/peter-edge/go-protoeasy
https://github.com/libopenstorage/openstorage
https://github.com/pachyderm/pachyderm
https://github.com/grpc/grpc-go
This also fixes golint errors (mostly package documentation), and go vet errors (some places in testing where t.Error should be t.Errorf, and where the wrong string directives were used).

Add a Makefile, and fix golint and go vet errors

---

web/func.go
web/func_test.go

ParseTruthyFalsy should evaluate empty strings as false rather than throwing an error. This can be useful for testing for missing URL parameters, for example.

modified ParseTruthyFalsy to evaluate empty strings as false

---

server/middleware.go
server/service.go
server/simple_server.go
server/simple_server_test.go

New context Service which using "golang.org/x/net/context" 
- context service
- simple test for context service
- generation of request-id and putting it to context

ContextService type for SimpleServer

---

web/func.go

%v is the default formatting flag, so just Sprint is enough.

web: simplify ParseTruthyFalsy a little further

---

examples/pubsub/api-sns-pub/service/cats_test.go
examples/servers/json/service/cats_test.go
examples/servers/json/service/mostpopular_test.go
examples/servers/mixed/service/mostpopular_test.go
examples/servers/mysql-saved-items/service/delete_test.go
examples/servers/mysql-saved-items/service/get_test.go
examples/servers/mysql-saved-items/service/put_test.go
examples/servers/rpc/service/cats_test.go
examples/servers/rpc/service/mostpopular_test.go
examples/servers/simple/service/mostpopular_test.go
server/rpc_server.go
server/server.go
server/simple_server.go
server/simple_server_test.go

This avoids having a global registry across different servers, and also avoids the need for always calling
metrics.DefaultRegistry.UnregisterAll() on some tests (sometimes on loop iterations, if you have a table-driven test).
Please let me know what you think of these changes!

Use server-scoped registry for metrics

---

config/aws.go
pubsub/aws.go
pubsub/awssub_test.go

By default, the SNS publisher base64 encodes the payload. On the SQS side, base64 decoding was _not_ the default and the current version will only base64 decode if the `config.SQS.ConsumeProtobuf` flag was set. 
To make the SQS subscriber's default compatible with SNS publisher's default, this will change that flag to be "true" by default.
Also, to better reflect what the flag is used for, I've renamed it from `ConsumeProtobuf` to `ConsumeBase64`.

Renaming `ConsumeProtobuf` to `ConsumeBase64` and defaulting to 'true'

---

examples/pubsub/sqs-sub/service/sub.go
pubsub/aws.go
pubsub/awssub_test.go

When consuming messages in goroutines, it's very possible that `Stop()` could be called while an SQSMessage is still being processed, resulting in a `panic` when attempting to mark the message as `Done()`.
To fix #30, this new implementation does not stop processing delete requests on `Stop()`. Instead, the number of in-flight messages is tracked and the delete handler will stop processing requests when the last message gets marked as `Done()`.

Allowing `SQSMessage.Done()` to be called after `SQSSubscriber.Stop()`

---

README.md
config/aws.go
config/config.go
doc.go

This PR adds an `ElastiCache` struct to the `config` package. The new struct has a `MustClient` method to return a `memcache.Client` connected to all nodes within the ElastiCache cluster.

Adding `config.ElastiCache` struct and helper

---

config/server.go
server/rpc_server.go
server/simple_server.go
server/simple_server_test.go

This PR allows to set different metrics registry to gizmo, to be able to use the same registry in gizmo and inside application.

Custom metrics registry for gizmo

---

config/mysql.go

Custom MySQL ports are not supported in config. This is useful for tunneled MySQL connections. If no port is specified, 3306 is the default.

Added support for custom MySQL ports

---

config/server.go
server/router.go
server/router_test.go
server/rpc_server.go
server/server.go
server/simple_server.go
server/simple_server_test.go
web/func.go
web/func_test.go

Gizmo users who need the performance of `julienschmidt/httprouter` more than the handy URL matching of Gorilla web toolkit's `mux`, can now configure the `server.SimplerServer` and `server.RPCServer` to use an alternate `Router` implementation. 
A new attribute in `config.Server`, `RouterType`, accepts the value `"gorilla"` (the default) to use Gorilla mux.Router or `"fast"` to use `httprouter.Router`.
To keep the use of idiomatic `http.Handler`s throughout Gizmo, instead of using `httprouter.Handle`, a new middleware function `HTTPToFastRoute` injects the `httprouter.Params` into a Gorilla request context. To retrieve the parameters, a new `web.Vars(r *http.Request) map[string]string` function is available and can be used like Gorilla's `mux.Vars`. The GorillaRouter also copies the …

Adding a new `server.Router` interface and `config.Server.RouterType` option with 2 implementations

---

config/flags.go
config/server.go
server/rpc_server.go
server/server.go
server/simple_server.go

nil = no log, "stdout" = os.Stdout, anything else logs to a file
I think this would only be a breaking change for folks who've configured the access log via code as opposed to via environment variable?

changing HTTPAccessLog to be a pointer

---

config/server.go
server/healthcheck.go
server/server.go

To allow users to create a custom health check handler, this PR adds a new `CustomHeathCheck` type that can be enabled by setting `config.Server.HealthCheckType` to `"custom"` and providing an `http.Handler` in `config.Server.CustomHealthCheckHandler` before passing the config to `server.Init()`.
Here's a simple example of adding a custom health check handler when using a JSON config:
```
config.LoadJSONFile("./config.json", &cfg)
+       cfg.Server.CustomHealthCheckHandler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+               io.WriteString(w, "hullo, sir!")
+       })
+
server.Init("nyt-simple-proxy", cfg.Server)
```
This example assumes the `HealthCheckType` attribute in the JSON has been set to "custom".

Adding `server.CustomHealthCheck` and `config.Server.CustomHealthCheckHandler`

---

pubsub/aws.go
pubsub/awssub_test.go
pubsub/kafka.go
pubsub/pubsub.go
pubsub/pubsubtest/sub.go

This method is defined to give more time for the handler of the massage
to handle it.  On AWS (and other queue systems), if Done is not called
within a certain amount of time, the message comes back to the queue,
calling ExtendDoneTimeout keeps the message out of the queue for the
given duration.
This behavior is not present in Kafka, so this method is a nop on Kafka.

pubsub: add method ExtendDoneTimeout to SubscriberMessage

---

config/aws.go

Without this fix LoadAWSFromEnv panics with the message "unable to load
env variable: specification must be a struct pointer".

config: fix LoadAWSFromEnv double indirection error

---

config/mongo.go

I'm not sure what relevant tests I can create for this. These new methods are just altering the state of the Session object, and there doesn't appear to be any tests currently on the configuration objects. If anyone has any ideas, I will be happy to include tests with this PR.

Support read preference and tag sets in Mongo configuration (#53)

---

server/server.go

This allows for more logging levels, as well as ignoring string case in the config.

Extended SetLogLevel to use ParseLevel in the logrus package.

---

config/config.go
config/metrics.go
config/server.go
examples/pubsub/sqs-sub/service/sub.go
examples/pubsub/sqs-sub/service/sub_test.go
server/metrics.go
server/metrics_test.go
server/router.go
server/rpc_server.go
server/server.go
server/simple_server.go
server/simple_server_test.go

* `config.Server.GraphiteHost` is now a deprecated config. 
* New `config.Metrics`, `config.Config.Metrics` and `config.Server.Metrics` handle all metrics configuration.
* Now able to integrate with statsd, dogstatsd, prometheus, expvar, graphite or nothing at all.
* Changes to emitted server route metric names:
* Counter names no longer have a `.count` suffix
* Histogram quantile names change from suffixes like `50-percentile` to `_50p`

Switching underlying metrics provider from `rcrowley/go-metrics` to `go-kit/kit/metrics`

---

README.md
config/config.go
config/gcp.go
config/metrics.go
doc.go
examples/pubsub/api-kafka-websocket-pubsub/service/stream.go
examples/pubsub/api-sns-pub/service/cats.go
examples/pubsub/cli-sns-pub/main.go
pubsub/aws.go
pubsub/awspub_test.go
pubsub/doc.go
pubsub/gcp.go
pubsub/gcp_test.go
pubsub/kafka.go
pubsub/pubsub.go
pubsub/pubsubtest/pub.go
server/doc.go
server/middleware.go
server/rpc_server.go
server/service.go
server/simple_server.go

This PR brings in some new types and tools for working with Google Cloud Platform:
* `config/GCP`: A helper config for working with Project IDs and contexts across development, App Engine, GCE and GKE
* `config/PubSub`: A helper config that is composed of a `config.GCP` and holds topics and subscription values.
* `pubsub/GCPSubscriber`: A pubsub implementation for subscribing to messages via GCP pubsub.
* `pubsub/GCPPublisher`: A pubsub implementation for publishing messages to GCP pubsub.
* `server/JSONContextEndpoint`: A new JSONEndpoint-like handler to work with `context.Context`
* `server/JSONContextService`: A new `Service` implementation composed of `JSONContextEndpoint`s that can register with a `SimpleServer`.
* `server/MixedContextService`: A new `Service` implementation composed …

Adding configs and pubsub implementations for GCP plus additional context endpoints and service types

---

pubsub/aws/awspub_test.go
pubsub/aws/awssub_test.go
pubsub/gcp/config.go
pubsub/gcp/gcp.go
server/config.go
server/server.go
server/simple_server.go

To allow Gizmo instances to seamlessly run on App Engine's Flexible VM environment, this PR adds a new "appengine" server type that hands over server management to Google by calling `appengine.Main()` on start up.
This PR also includes a few small bugs in the pubsub/gcp package that we ran into while using Gizmo's pubsub package within a Gizmo "appengine" type server.

Adding new "appengine" server.Config.Type to allow SimpleServer to run on App Engine Flexible VMs + PubSub fixes

---

config/gcp/gcp.go
pubsub/gcp/gcp.go
pubsub/gcp/gcp_test.go

This PR resolves issue #66 by changing the import paths and dealing with changes to initiating GCP clients.
There are 3 breaking changes:
* package `config/gcp` has replaced `NewContext` with `ClientOption`. Users should use `ClientOption()` to authorize any GCP clients instead of using a context object.
* package `pubsub/gcp` has added some additional parameters to the constructors to deal with these changes.
* `pubsub/gcp.SubscriberMessage.ExtendDoneDeadline` is no longer a valid method

Switching out google.golang.org for cloud.google.com

---

server/metrics.go
server/rpc_server.go
server/simple_server.go

As discussed with @jprobinson - this fixes Prometheus metrics in gizmo by
- not using invalid metric names but using the standard prometheus.InstrumentHandler() that will generate http_* metrics and use the full endpoint pathname as a label.
- expose prometheus metrics at `/metrics`
🍺

Fix and refactor prometheus metrics setup

---

pubsub/aws/aws.go

Since the default log level on Sirupsen/logrus is `info`, the Gizmo pubsub/aws module is currently creating noise in my logs unless I change my default log level.
My suggestion in this PR is to send the logging messages in the pubsub/aws module to the `debug` level instead.
Please review.

pubsub/aws: send log messages to debug level

---

server/router.go
web/func.go
web/func_test.go
web/vars_gorilla.go
web/vars_native.go

This fix adds build tags around the `web.SetRouteVars` and `web.Vars` functions similar to the new tags in `gorilla/mux` for 1.7. The tags will use `gorilla/context` for <1.7 and the new native `context` package for 1.7.
This does introduce a small breaking change to `web.SetRouteVars` as it now requires you to use the `*http.Request` returned by that func, but after a quick github search I can see no one outside of gizmo (and other things I personally own) that will be affected.
This should fix issue #74.

Fixing memory leak caused by routers in 1.7

---

examples/servers/mysql-saved-items/service/service.go
server/context_gorilla.go
server/context_native.go
server/router.go
server/server.go
server/simple_server.go
web/func.go
web/func_test.go
web/vars_gorilla.go
web/vars_native.go

This should remove the remaining uses of `gorilla/context` in the server to clean up the memory leaks. This PR also updates one of the examples to show how to deal with Gorilla memory leaks going forward via the `context.ClearHandler` middleware.
I'm planning on running a few load tests tomorrow to verify these fixes, so please do not merge quite yet.

Cleaning up the rest of gorilla/context use for Go 1.7

---

server/rpc_server.go

`golint` now enforces the convention that `context.Context` should be the first parameter in any function call it exists in, which I agree with.
This introduces a small breaking change, but only to our `RPCServer` tools which are already flagged as 'experimental'.

Updating `LogRPCWithFields` to match new `golint` conventions

---

README.md
pubsub/gcp/gcp.go
pubsub/pubsub.go
pubsub/pubsubtest/pub.go

The `Publisher` interface only allows for publishing a single message at a time. We're working with bulk API endpoints where we need to publish 50-100 messages at once. I spoke with @jprobinson on the #gizmo channel about this contribution.
This PR introduces a `MultiPublisher` interface that supports a `PublishMulti` method that looks like this:
`PublishMulti(ctx context.Context, keys []string, messages []proto.Message) error`
While JP originally suggested adding this to the `Publisher` interface, as soon as I started digging in I realized not all publishers support this feature, like AWS SNS. See [here](https://forums.aws.amazon.com/thread.jspa?messageID=639931#639931) and [here](https://forums.aws.amazon.com/thread.jspa?messageID=592007))
As a result I opted to create a new interface …

Add MultiPublisher pubsub interface

---

README.md
examples/servers/rpc/service/nyt-proxy.pb.go
pubsub/gcp/gcp_http.go

I found out yesterday using the default Google PubSub client in App Engine's standard environment to publish actually counts against the 'socket' quota (which only allows for 3.4MM requests per day).
I've found that publishing via plain HTTP will _not_ count against the quota so this PR adds a new `Publisher` implementation that uses the generated HTTP client (google.golang.org/api/pubsub/v1) instead of the gRPC based client (cloud.google.com/go/pubsub).

Adding a new HTTP Publisher type to `pubsub/gcp` for App Engine use

---

README.md
pubsub/gcp/gcp.go
pubsub/gcp/gcp_http.go
pubsub/pubsub.go

This branch changes the GCP publishers to return `MultiPublisher`, which also (now) embeds the singular publisher, allowing GCP publishers to use the `MultiPublisher` methods.

Refinements to pubsub.MultiPublisher

---

server/metrics.go

It's actually `*provider.prometheusProvider`

Fix type name when using Prometheus metrics

---

server/rpc_server.go

Hello Gizmos,
while playing with your framework I ran into a problem with the `MonitorRPCRequest`-method.
I had a little typo in the second parameter (the method name) which was so subtle, that it took me like a full working day to figure it out. When I finally looked at the right spot (adding a couple of console outputs into the `server/rpc_server.go` implementation) I finally noticed that `m` is nil in case of an invalid methodName.
In that case the generated error message is not really helpful:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6d800]
```
I spent a lot of time looking into my handling of errors, because there was a lot of referencing/dereferencing going on... So I basically wasted …

Error message added to MonitorRPCRequest in server/rpc_server.go

---

examples/servers/rpc/service/cats.go
examples/servers/rpc/service/mostpopular.go
server/rpc_server.go

Hello there NYT-Team,
I found an unfortunate bug in your RPC-Server implementation.
It's again the MonitorRPCRequest function that concerns me.
While writing my last PR I already spotted this, but forgot to have a look at it.
In your RPC example the cat and mostpopular handlers both have the `defer server.MonitorRPCRequest()(ctx, "GetCats", err)` as first line. This is perfectly fine, as a `rescue()`(which is executed within the function) should always be called very early in a critical function call.
The problem is, that in case of an error, the metrics will still count a success instead of an error.
Please refer to the explanation of `defer` from https://blog.golang.org/defer-panic-and-recover
> 1. A deferred function's arguments are evaluated when the defer statement is evaluated.
The …

fixed a bug in the MonitorRPCRequest function of the RPCServer

---

pubsub/kafka/kafka.go

With the latest `sarama` library the `sconfig.Producer.Return.Successes` configuration value must be _true_ for the Sync Producer. Failing to configure this produces an error from `NewPublisher()` as in:
```
kafka: invalid configuration (Producer.Return.Successes must be true to be used in a SyncProducer)
```

Add sconfig.Producer.Return.Successes value

---

server/server.go

This is causing issues for us then HealthcheckType = "esx" cause ESX seems to be using HEAD

Handle method GET and HEAD for healthcheck requests

---

server/server.go

Trace can be used like this:
```
$ wget http://localhost:8080/debug/pprof/trace?seconds=5 -O trace.out
$ go tool trace trace.out'
```

Add pprof trace endpoint

---

examples/servers/kit/config.sh
server/kit/config.go
server/kit/kitserver.go
server/kit/kitserver_test.go
server/kit/server.go

- removing package level variables
- only allowing for env variable configuration
- cleaning up (and adding to) default configuration management
- removing all other gizmo libs
- adding end-to-end test that relies on cat example
- adding basic health check & ability to override with custom health check

Cleaning up the kit server

---

server/kit/kitserver.go
server/kit/server.go

This adds a `NewServer(s Service) *Server` so users can then call `server.ServeHTTP(w, r)` to run unit tests against their handlers.

Exposing server/kit.Server for unit testing

---

pubsub/gcp/gcp.go
pubsub/gcp/gcp_test.go

- Makes gcp.subscriber public
- Makes gcp.subscribeImpl.sub public
- Applies case changes to tests
I've changed as little as possible to keep backward compatibility. The `subscribeImpl` is kept for testing but i've made it's .sub variable public so the new `SetReceiveSettings` function can access the underlying `gpubsub.Subscription`.
The `gcp.NewSubscriber` function now returns an `gcp.Subscriber` but old code expecting the `pubsub.Subscriber` will still continue to work.
Please let me know if you see any improvements.

Adds SetReceiveSettings to Subscriber

---

server/kit/kitserver.go
server/kit/server.go
server/kit/server_gae.go

The `syscall` reference in the server made it impossible for an App Engine project to reference a package using this library.
This PR splits the `kit.Run` implementation via build tags so syscall isn't referenced in GAE.

making server/kit projects available to GAE users

---

pubsub/gcp/gcp.go
pubsub/gcp/gcp_test.go

Just like my last pull request adding a function to Subscriber, this pull request adds a function to SubMessage making the underlying attributes sent with GCP accessible.

Makes gcp attributes accessible

---

Makefile
examples/servers/kit/api/service.go
server/kit/kitserver.go
server/kit/kitserver_test.go
server/kit/service.go

I ran into this problem while attempting to add [Google Cloud's Trace middleware](https://godoc.org/cloud.google.com/go/trace#Client.GRPCServerInterceptor) via the `kit.Service.RPCOptions()` method, but ran into the fact that only one [UnaryInterceptor](https://godoc.org/google.golang.org/grpc#UnaryInterceptor) can be installed.
This adds 1 more method to he `kit.Service` interface that allows users to add interceptors while still allowing gizmo to inject its logger and `kit.Server.Middleware`.

adding kit.Service.RPCMiddlware because grpc only allows for 1 unary server interceptor

---

examples/nyt/client.go

I found a dropped error variable in the client example for the nyt package.

Fix swallowed err in client example.

---

examples/servers/reading-list/README.md

The most piddly of PRs, but almost immediately upon looking at this example after it was announced in slack#go-kit, I clicked on the drone link in the readme and got a 404.

Fix .drone.yml link and typo in README.md

---

examples/servers/reading-list/get.go
examples/servers/reading-list/service.go
server/kit/kitserver.go
server/kit/kitserver_test.go
server/kit/log.go

Adding a blank server logger to the context was fairly worthless (and kinda dirty) as it allows users to log without any metadata.
This change automatically adds all request context metadata/headers to the logger _one_ time when it is injected into the context and consequently removes the '*WithFields' functions for the logger as the fields are _always_ there.

[server/kit] Always adding context values to request scoped logger

---

server/kit/kitserver.go
server/kit/kitserver_test.go

This is my attempt at resolving the problems discussed in #125 without adding channels to the server.
@alrs, how do you feel about these changes?

[server/kit] filtering out expected shutdown errors & capturing test errors properly

---

server/kit/kitserver.go

This is a handy set of profiling endpoints that get added to the simple server by default.
We should have these available in the new kit server as well.

adding pprof endpoints to all kit servers by default

---

pubsub/aws/awssub_test.go
server/kit/config.go
server/kit/kitserver.go
server/kit/kitserver_test.go
server/middleware.go
server/rpc_server.go
server/simple_server.go
server/simple_server_test.go

Up until now, the servers have all had middleware stacked like this:
```
Router => HTTP Middleware => Context Middleware (optional) => JSON Middleware (optional) => Endpoint
```
This has led to pains with things like CORS where it'd be nice to have a global middleware for auto-accepting `OPTIONS`-style requests. In the current setup, folks are forced to register an additional `OPTIONS` route for each endpoint (issue #129).
This PR alters the order of middleware so that such global rules are possible due to the new stack:
```
HTTP Middleware => Router => Context Middleware (optional) => JSON Middleware (optional) => Endpoint
```
Resolves #129
Also, the SQS interface updated again so this PR includes some updates for tests to pass.

[server] Moving HTTP middleware above the Router

---

server/router.go
server/router_test.go
server/rpc_server.go
server/simple_server.go

Attempting to fix #132 without rolling back our middleware changes.
The server now checks for Gorilla routers and uses the mux to match/lookup the incoming path's template, if any.
One caveat is that unmatched paths will still cause a new metric to be created for them. Probably wise to monitor your 404s.
Since I was only able to get this fixed for Gorilla and not httprouter, I've decided to deprecate the httprouter (FastRouter) implementation.

[server] Look up route template for metric names, deprecate httprouter

---

config/aws/aws.go
pubsub/aws/aws.go
pubsub/aws/config.go

Adds few extra config values `RoleARN`, `MFASerialNumber` and `QueueOwnerAWSAccountId`
If `RoleARN` is set, the credentials are replaced with the one provided by AssumeRole
https://docs.aws.amazon.com/sdk-for-go/api/service/sts/#hdr-Using_MFA_with_AssumeRole
if `MFASerialNumber` is set, then the user will be prompted to insert the MFA code (using the `stscreds.StdinTokenProvider`)
Closes #134

Add support for AssumeRoleProvider Role credentials with optional MFA

---

server/rpc_server.go
server/server.go
server/simple_server.go
server/simple_server_test.go

I would like to fix #19 . Added a `server.ErrMultiRegister` error which is returned if the `server.Register(service)` is called multiple times. 
Updated the `SimpleServer`'s `TestBasicRegistration` test to make it pass.

Added ErrMultiRegister on multiple Register calls

---

server/metrics.go
server/simple_server.go

- remove deprecated function calls (summary metric has been removed as well inside Prometheus)
- improve counter and timer for endpoints to use provided by promhttp package instruments 
PS. Stackdriver supports histograms.

Improve Prometheus metrics

---

server/metrics.go
server/simple_server.go

Reverts NYTimes/gizmo#141
Explanation here: https://github.com/NYTimes/gizmo/pull/141/files#r193066478
Can we please rollback the original PR? It completely breaks prometheus integration for our services and uses multiple metrics where really labels should be used.

Revert "Improve Prometheus metrics"

---

pubsub/aws/aws.go
pubsub/aws/config.go

Add a `SqsQueueURL` field to `aws/config.go` to override queue name and queue owner account ID.
This new field, when provided, will take precedence over the queue name.
Reason: providing queue name and owner account ID is cumbersome for the case when the queue URL is already given.
In this case directly using the URL is preferable.

Add SQS Queue URL to SQS config to simplify configuration of SQS Subscriber

---

config/aws/aws.go
pubsub/aws/aws.go

Currently, using temp credentials is only possible via environment. 
Basically, calling `awsCfg := aws.LoadSQSConfigFromEnv()` will work fine because it will set the `SessionToken` field in AWS credentials config correctly.
However, If one requires to configure the client in code, i.e. setting the fields of `aws.SQSConfig` in code, then there is no way to pass session token down to the client. So, there is no way to correctly initialise an SQS Subscriber by filling the SQSConfig in the code. 
Workarounds are possible, but this PR is to add the necessary config field that a caller can set.

Add AWS_SESSION_TOKEN into aws.Config to allow using temporary credentials

---

config/aws/aws.go
pubsub/aws/aws.go

The AWS service endpoint can be overridden to enable emulation. For example by using localstack. Fixes https://github.com/NYTimes/gizmo/issues/156

Allow overriding of AWS endpoint

---

server/kit/README.md
server/kit/gae_log.go
server/kit/kitserver.go
server/kit/log.go

If the `GAE_VERSION` environment variable is set (automatically done by the GAE platform), the server will use the new `gaeLogger`. By default, the server will still use the go-kit JSON `log.Logger`. 
This new addition gives us the same feel as we had for the 1st generation runtime. All application level logs that occur during a request will be tied to the access request log in the Google console.
This change will detect the use of kit/log/levels and automatically translate them to Stackdriver's Severity levels.
One breaking change to the logger is the use of `kit.LogMsg` and `kit.LogErrorMsg` will now use the string `message` instead of `msg` for the log key. This is to be compliant with stackdriver's logging formats.

[server/kit] Adding automatic Stackdriver logging for App Engine 2nd generation runtime

---

server/kit/kitserver.go
server/kit/kitserver_test.go

also, warm up and health check requests are now wrapped with all the other middlewares of the app.

[server/kit] automatically registering "warm up" endpoint for GAE users

---

pubsub/aws/aws.go

To allow for mocking of SQS queues a configurable endpoint is required. For SNS this has already been done, this is just adding the same for SQS.
This is my first contribution so I hope I've follow the process
Resolves #165

Update SQS constructor to allow custom AWS endpoint

---

auth/gcp/iam.go
auth/gcp/identity.go
go.mod
go.sum

Using the google accounts hostname as an issuer was not the right route. IAM users generally set the service account email itself as the issuer and subject: https://cloud.google.com/endpoints/docs/openapi/service-account-authentication#using_jwt_signed_by_service_account

[auth/gcp] properly setting the service account email as the issuer and subject for IAM

---

config/aws/aws.go
pubsub/aws/aws.go

For background, we run our application in a k8s container with an AWS role with SQS & SNS permissions already configured. We've been using a gizmo fork that doesn't configure credentials without trouble for the last few months.

Remove explicit call to use credentials from environment variables

---

server/kit/kitserver.go
server/kit/log.go
server/kit/sd_log.go

This will allow to log to Stackdriver with environment specific information, like instance_id, namespace, etc. for GKE

Add resource information to logger of GKE, GCE and AWS EC2

---

go.mod
go.sum
server/kit/router.go
server/router.go
server/router_test.go

Fixes https://github.com/NYTimes/gizmo/issues/190 :v:

Remove Deprecated Fast Router

---

server/kit/kitserver.go

This is to resolve the same issue as https://github.com/NYTimes/gizmo/issues/184, but for the kit server.

[server/kit] Removing multiple middleware calls

---

config/mysql/mysql.go
config/postgresql/postgresql.go

`String()` mutating the object can cause problems of a doubly query escaped location string. For instance in this example:
```
cfg := mysql.LoadConfigFromEnv()
log.Println(cfg)
db, err := cfg.DB()
if err != nil {
panic(err)
}
```
`String()` called by the logger will mutate `m.Location` with query escape. The subsequent `String()` call via `cfg.DB()` will lead to the doubly query escaped string. If there is no specific reason as to why `String()` should have these side effects it might be good not to mutate the object?
cc @bajh

String() should not mutate object

---

server/kit/config.go

This will be handy in places like App Engine where the port they want you to run on is injected into the `PORT` environment variable.

[server/kit] falling back to PORT env variable if HTTP_PORT is not set

---

auth/verify.go
auth/verify_test.go

I've found I handle auth in Gizmo's HTTPMiddleware more often than within the go-kit Middleware.
Because of that, I've found myself implementing a func to parse the "Authorization" header several times.
This provides a new method to make that a cleaner experience.

[auth] adding VerifyRequest for use within http middlewares

---

go.sum
server/kit/kitserver.go

According to the docs, `Start` will attempt to pull the service info from the environment, but passing what we've already collected should allow our stats to be consistent across profiling, trace and logging.
More details here: https://cloud.google.com/profiler/docs/profiling-go

[server/kit] adding Google profiler if environment is GCP enabled

---

observe/observe.go
server/kit/kitserver.go
server/kit/log.go

I've been using the gizmo/server.SimpleServer on App Engine as I upgrade some legacy projects from 1.9 to the new world of 1.11+ and would like to have a nicer experience around monitoring in that realm.
To cut out the amount of boilerplate required to initiate tracing and metrics, I'm proposing a new `RegisterAndObserveGCP` that will do all that the `kit` server does on startup minus the Stackdriver error reporting as that would require additional hooks into the server.

[observe] Adding RegisterAndObserveGCP to use within the SimpleServer (or any non-sever/kit poject))

---

.travis.yml
auth/gcp/identity.go
auth/keys.go
auth/verify.go

The `auth.Verifier.Verify` method can return an `error` -- However, there's no way to know if that error happened because the client sent bad credentials, or if that error happened because of an internal server error (for example, the google certs URL not properly returning public keys)
This PR adds a public error that can be checked with `errors.Cause(err) == auth.ErrBadCreds`. If true, the caller can assume that this is a *client* side error and not a *server* error.

auth: expose ErrBadCreds to check for expected errs

---

server/config.go
server/router.go

This adds a `stdlib` implementation to the package thats very similar to the [server/kit] implementation.
I have a server I'm moving from our internal GAE framework to our old friend gizmo/server and have the need to rely on a `stdlib` style router.

[server] adding a stdlib router

---

server/router_test.go
server/server.go
server/simple_server_test.go

The health checks were registering on both the GET and HEAD methods, which was causing the `http.ServeMux` to panic on startup.
This adds a check to fix that and also removes some old tests referencing the no-longer existent "fast" router.

[server] fixing stdlib router 😅

---

pubsub/aws/aws.go

The suggested fix for issue #131

Allow to set SNS Message Attributes via context

---

pubsub/aws/aws.go

@jprobinson sorry for troubles, but I just realized that there is typo in the method name :/

fix typo in the WithMessageAttributes method
